-- Auto-generated by scripts/firebase-import.ts
-- Generated: 2026-07-04T17:03:46.272Z
BEGIN;

INSERT INTO "Subject" ("id", "name") VALUES ('sub_Physics', 'Physics') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Subject" ("id", "name") VALUES ('sub_Chemistry', 'Chemistry') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Subject" ("id", "name") VALUES ('sub_Maths', 'Maths') ON CONFLICT ("name") DO NOTHING;
INSERT INTO "Subject" ("id", "name") VALUES ('sub_CustomSubject', 'Custom Subject') ON CONFLICT ("name") DO NOTHING;

INSERT INTO "Student" (
  "id", "batchId", "rollNo", "fullName", "schoolName", "subjectsText", "subjectCount",
  "grade", "board", "contact", "feesStatus", "feesAmountPaid", "feesRemaining", "feesDatePaid",
  "deletedAt", "deletedFromBatch", "guardianPhone", "enrollmentDate"
) VALUES (
  'id1',
  (SELECT "id" FROM "Batch" WHERE "name" = '12 CBSE'),
  1,
  'Alan Bygy',
  'Example School',
  'Physics, Chemistry, Maths',
  3,
  '12',
  'CBSE',
  '9876543210',
  'PENDING',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '',
  NOW()
) ON CONFLICT ("id") DO UPDATE SET
  "batchId" = EXCLUDED."batchId",
  "rollNo" = EXCLUDED."rollNo",
  "fullName" = EXCLUDED."fullName",
  "schoolName" = EXCLUDED."schoolName",
  "subjectsText" = EXCLUDED."subjectsText",
  "subjectCount" = EXCLUDED."subjectCount",
  "contact" = EXCLUDED."contact",
  "feesStatus" = EXCLUDED."feesStatus",
  "feesAmountPaid" = EXCLUDED."feesAmountPaid",
  "feesRemaining" = EXCLUDED."feesRemaining",
  "feesDatePaid" = EXCLUDED."feesDatePaid",
  "deletedAt" = EXCLUDED."deletedAt",
  "deletedFromBatch" = EXCLUDED."deletedFromBatch";
INSERT INTO "RegisterMark" ("id", "studentId", "exam", "subject", "score", "date")
VALUES ('mark_m1', 'id1', 'Monthly Test', 'Physics', '42/50', '2025-03-15T10:00:00.000Z')
ON CONFLICT ("id") DO NOTHING;
INSERT INTO "RegisterDocument" ("id", "studentId", "title", "dataUrl", "uploadedAt")
VALUES ('doc_d1', 'id1', 'ID Proof', 'data:image/png;base64,iVBORw0KGgo=', '2025-03-01T08:00:00.000Z')
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "Student" (
  "id", "batchId", "rollNo", "fullName", "schoolName", "subjectsText", "subjectCount",
  "grade", "board", "contact", "feesStatus", "feesAmountPaid", "feesRemaining", "feesDatePaid",
  "deletedAt", "deletedFromBatch", "guardianPhone", "enrollmentDate"
) VALUES (
  'id99',
  NULL,
  5,
  'Removed Student',
  'Old School',
  'Maths',
  NULL,
  '10',
  'CBSE',
  NULL,
  'PAID',
  5000,
  NULL,
  NULL,
  '2025-06-01T12:00:00.000Z',
  '10 CBSE',
  '',
  NOW()
) ON CONFLICT ("id") DO UPDATE SET
  "batchId" = EXCLUDED."batchId",
  "rollNo" = EXCLUDED."rollNo",
  "fullName" = EXCLUDED."fullName",
  "schoolName" = EXCLUDED."schoolName",
  "subjectsText" = EXCLUDED."subjectsText",
  "subjectCount" = EXCLUDED."subjectCount",
  "contact" = EXCLUDED."contact",
  "feesStatus" = EXCLUDED."feesStatus",
  "feesAmountPaid" = EXCLUDED."feesAmountPaid",
  "feesRemaining" = EXCLUDED."feesRemaining",
  "feesDatePaid" = EXCLUDED."feesDatePaid",
  "deletedAt" = EXCLUDED."deletedAt",
  "deletedFromBatch" = EXCLUDED."deletedFromBatch";

INSERT INTO "PendingAdmission" ("id", "name", "schoolName", "subjects", "subjectCount", "contact", "batchName", "submittedAt")
VALUES (
  'pending1',
  'New Applicant',
  'St. Mary''s',
  'PCM',
  3,
  '9999999999',
  '12 CBSE',
  '2025-07-01T09:00:00.000Z'
) ON CONFLICT ("id") DO NOTHING;

COMMIT;